<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Register Test "
           tests="3"
           failures="1"
           errors="0"
           skipped="0"
           time="12.513">
  <properties />
            <testcase name="logout" time="1.510" classname="automationPractice.base.RegisterUser">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
	Customer has not logged out expected [Loginto your account] but found [Login to your account]"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
	Customer has not logged out expected [Loginto your account] but found [Login to your account]
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
  automationPractice.base.RegisterUser.logout(RegisterUser.java:37)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:566)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
  org.testng.TestRunner.privateRun(TestRunner.java:848)
  org.testng.TestRunner.run(TestRunner.java:621)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
  org.testng.SuiteRunner.run(SuiteRunner.java:336)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
  org.testng.TestNG.runSuites(TestNG.java:1114)
  org.testng.TestNG.run(TestNG.java:1082)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="loginWithCorrectEmailnPass" time="5.747" classname="automationPractice.base.RegisterUser" />
                <testcase name="loginWithCorrectEmailnPass" time="5.256" classname="automationPractice.base.RegisterUser" />
      
</testsuite>
